// GENERATED from themes-index.json — do not edit by hand.

export type Appearance = "dark" | "light"

export interface GhosttyThemeMeta {
  slug: string
  name: string
  appearance: Appearance
  /** background hex — for picker swatches */
  bg: string
  /** foreground hex — for picker swatches */
  fg: string
}

/** All Ghostty themes (slug, name, appearance, bg, fg). */
export const GHOSTTY_THEMES: GhosttyThemeMeta[] = [
  { slug: "0x96f", name: "0x96f", appearance: "dark", bg: "#262427", fg: "#fcfcfa" },
  { slug: "12-bit-rainbow", name: "12-bit Rainbow", appearance: "dark", bg: "#040404", fg: "#feffff" },
  { slug: "3024-day", name: "3024 Day", appearance: "light", bg: "#f7f7f7", fg: "#4a4543" },
  { slug: "3024-night", name: "3024 Night", appearance: "dark", bg: "#090300", fg: "#a5a2a2" },
  { slug: "aardvark-blue", name: "Aardvark Blue", appearance: "dark", bg: "#102040", fg: "#dddddd" },
  { slug: "abernathy", name: "Abernathy", appearance: "dark", bg: "#111416", fg: "#eeeeec" },
  { slug: "adventure", name: "Adventure", appearance: "dark", bg: "#040404", fg: "#feffff" },
  { slug: "adventure-time", name: "Adventure Time", appearance: "dark", bg: "#1f1d45", fg: "#f8dcc0" },
  { slug: "adwaita", name: "Adwaita", appearance: "light", bg: "#ffffff", fg: "#000000" },
  { slug: "adwaita-dark", name: "Adwaita Dark", appearance: "dark", bg: "#1d1d20", fg: "#ffffff" },
  { slug: "afterglow", name: "Afterglow", appearance: "dark", bg: "#212121", fg: "#d0d0d0" },
  { slug: "alabaster", name: "Alabaster", appearance: "light", bg: "#f7f7f7", fg: "#000000" },
  { slug: "alien-blood", name: "Alien Blood", appearance: "dark", bg: "#0f1610", fg: "#637d75" },
  { slug: "andromeda", name: "Andromeda", appearance: "dark", bg: "#262a33", fg: "#e5e5e5" },
  { slug: "apple-classic", name: "Apple Classic", appearance: "dark", bg: "#2c2b2b", fg: "#d5a200" },
  { slug: "apple-system-colors", name: "Apple System Colors", appearance: "dark", bg: "#1e1e1e", fg: "#ffffff" },
  { slug: "apple-system-colors-light", name: "Apple System Colors Light", appearance: "light", bg: "#feffff", fg: "#000000" },
  { slug: "arcoiris", name: "Arcoiris", appearance: "dark", bg: "#201f1e", fg: "#eee4d9" },
  { slug: "ardoise", name: "Ardoise", appearance: "dark", bg: "#1e1e1e", fg: "#eaeaea" },
  { slug: "argonaut", name: "Argonaut", appearance: "dark", bg: "#0e1019", fg: "#fffaf4" },
  { slug: "arthur", name: "Arthur", appearance: "dark", bg: "#1c1c1c", fg: "#ddeedd" },
  { slug: "atelier-sulphurpool", name: "Atelier Sulphurpool", appearance: "dark", bg: "#202746", fg: "#979db4" },
  { slug: "atom", name: "Atom", appearance: "dark", bg: "#161719", fg: "#c5c8c6" },
  { slug: "atom-one-dark", name: "Atom One Dark", appearance: "dark", bg: "#21252b", fg: "#abb2bf" },
  { slug: "atom-one-light", name: "Atom One Light", appearance: "light", bg: "#f9f9f9", fg: "#2a2c33" },
  { slug: "aura", name: "Aura", appearance: "dark", bg: "#15141b", fg: "#edecee" },
  { slug: "aurora", name: "Aurora", appearance: "dark", bg: "#23262e", fg: "#ffca28" },
  { slug: "ayu", name: "Ayu", appearance: "dark", bg: "#0b0e14", fg: "#bfbdb6" },
  { slug: "ayu-light", name: "Ayu Light", appearance: "light", bg: "#f8f9fa", fg: "#5c6166" },
  { slug: "ayu-mirage", name: "Ayu Mirage", appearance: "dark", bg: "#1f2430", fg: "#cccac2" },
  { slug: "banana-blueberry", name: "Banana Blueberry", appearance: "dark", bg: "#191323", fg: "#cccccc" },
  { slug: "batman", name: "Batman", appearance: "dark", bg: "#1b1d1e", fg: "#6f6f6f" },
  { slug: "belafonte-day", name: "Belafonte Day", appearance: "light", bg: "#d5ccba", fg: "#45373c" },
  { slug: "belafonte-night", name: "Belafonte Night", appearance: "dark", bg: "#20111b", fg: "#968c83" },
  { slug: "birds-of-paradise", name: "Birds Of Paradise", appearance: "dark", bg: "#2a1f1d", fg: "#e0dbb7" },
  { slug: "black-metal", name: "Black Metal", appearance: "dark", bg: "#000000", fg: "#c1c1c1" },
  { slug: "black-metal-bathory", name: "Black Metal (Bathory)", appearance: "dark", bg: "#000000", fg: "#c1c1c1" },
  { slug: "black-metal-burzum", name: "Black Metal (Burzum)", appearance: "dark", bg: "#000000", fg: "#c1c1c1" },
  { slug: "black-metal-dark-funeral", name: "Black Metal (Dark Funeral)", appearance: "dark", bg: "#000000", fg: "#c1c1c1" },
  { slug: "black-metal-gorgoroth", name: "Black Metal (Gorgoroth)", appearance: "dark", bg: "#000000", fg: "#c1c1c1" },
  { slug: "black-metal-immortal", name: "Black Metal (Immortal)", appearance: "dark", bg: "#000000", fg: "#c1c1c1" },
  { slug: "black-metal-khold", name: "Black Metal (Khold)", appearance: "dark", bg: "#000000", fg: "#c1c1c1" },
  { slug: "black-metal-marduk", name: "Black Metal (Marduk)", appearance: "dark", bg: "#000000", fg: "#c1c1c1" },
  { slug: "black-metal-mayhem", name: "Black Metal (Mayhem)", appearance: "dark", bg: "#000000", fg: "#c1c1c1" },
  { slug: "black-metal-nile", name: "Black Metal (Nile)", appearance: "dark", bg: "#000000", fg: "#c1c1c1" },
  { slug: "black-metal-venom", name: "Black Metal (Venom)", appearance: "dark", bg: "#000000", fg: "#c1c1c1" },
  { slug: "blazer", name: "Blazer", appearance: "dark", bg: "#0d1926", fg: "#d9e6f2" },
  { slug: "blue-berry-pie", name: "Blue Berry Pie", appearance: "dark", bg: "#1c0c28", fg: "#babab9" },
  { slug: "blue-dolphin", name: "Blue Dolphin", appearance: "dark", bg: "#006984", fg: "#c5f2ff" },
  { slug: "blue-matrix", name: "Blue Matrix", appearance: "dark", bg: "#101116", fg: "#00a2ff" },
  { slug: "bluloco-dark", name: "Bluloco Dark", appearance: "dark", bg: "#282c34", fg: "#b9c0cb" },
  { slug: "bluloco-light", name: "Bluloco Light", appearance: "light", bg: "#f9f9f9", fg: "#373a41" },
  { slug: "borland", name: "Borland", appearance: "dark", bg: "#0000a4", fg: "#ffff4e" },
  { slug: "box", name: "Box", appearance: "dark", bg: "#141d2b", fg: "#9fef00" },
  { slug: "breadog", name: "Breadog", appearance: "light", bg: "#f1ebe6", fg: "#362c24" },
  { slug: "breeze", name: "Breeze", appearance: "dark", bg: "#31363b", fg: "#eff0f1" },
  { slug: "bright-lights", name: "Bright Lights", appearance: "dark", bg: "#191919", fg: "#b3c9d7" },
  { slug: "broadcast", name: "Broadcast", appearance: "dark", bg: "#2b2b2b", fg: "#e6e1dc" },
  { slug: "brogrammer", name: "Brogrammer", appearance: "dark", bg: "#131313", fg: "#d6dbe5" },
  { slug: "builtin-dark", name: "Builtin Dark", appearance: "dark", bg: "#000000", fg: "#bbbbbb" },
  { slug: "builtin-light", name: "Builtin Light", appearance: "light", bg: "#ffffff", fg: "#000000" },
  { slug: "builtin-pastel-dark", name: "Builtin Pastel Dark", appearance: "dark", bg: "#000000", fg: "#bbbbbb" },
  { slug: "builtin-solarized-dark", name: "Builtin Solarized Dark", appearance: "dark", bg: "#002b36", fg: "#839496" },
  { slug: "builtin-solarized-light", name: "Builtin Solarized Light", appearance: "light", bg: "#fdf6e3", fg: "#657b83" },
  { slug: "builtin-tango-dark", name: "Builtin Tango Dark", appearance: "dark", bg: "#000000", fg: "#ffffff" },
  { slug: "builtin-tango-light", name: "Builtin Tango Light", appearance: "light", bg: "#ffffff", fg: "#000000" },
  { slug: "c64", name: "C64", appearance: "dark", bg: "#40318d", fg: "#7869c4" },
  { slug: "cga", name: "CGA", appearance: "dark", bg: "#000000", fg: "#aaaaaa" },
  { slug: "clrs", name: "CLRS", appearance: "light", bg: "#ffffff", fg: "#262626" },
  { slug: "calamity", name: "Calamity", appearance: "dark", bg: "#2f2833", fg: "#d5ced9" },
  { slug: "carbonfox", name: "Carbonfox", appearance: "dark", bg: "#161616", fg: "#f2f4f8" },
  { slug: "catppuccin-frappe", name: "Catppuccin Frappe", appearance: "dark", bg: "#303446", fg: "#c6d0f5" },
  { slug: "catppuccin-latte", name: "Catppuccin Latte", appearance: "light", bg: "#eff1f5", fg: "#4c4f69" },
  { slug: "catppuccin-macchiato", name: "Catppuccin Macchiato", appearance: "dark", bg: "#24273a", fg: "#cad3f5" },
  { slug: "catppuccin-mocha", name: "Catppuccin Mocha", appearance: "dark", bg: "#1e1e2e", fg: "#cdd6f4" },
  { slug: "chalk", name: "Chalk", appearance: "dark", bg: "#2b2d2e", fg: "#d2d8d9" },
  { slug: "chalkboard", name: "Chalkboard", appearance: "dark", bg: "#29262f", fg: "#d9e6f2" },
  { slug: "challenger-deep", name: "Challenger Deep", appearance: "dark", bg: "#1e1c31", fg: "#cbe1e7" },
  { slug: "chester", name: "Chester", appearance: "dark", bg: "#2c3643", fg: "#ffffff" },
  { slug: "ciapre", name: "Ciapre", appearance: "dark", bg: "#191c27", fg: "#aea47a" },
  { slug: "citruszest", name: "Citruszest", appearance: "dark", bg: "#121212", fg: "#bfbfbf" },
  { slug: "cobalt-neon", name: "Cobalt Neon", appearance: "dark", bg: "#142838", fg: "#8ff586" },
  { slug: "cobalt-next", name: "Cobalt Next", appearance: "dark", bg: "#162c35", fg: "#d7deea" },
  { slug: "cobalt-next-dark", name: "Cobalt Next Dark", appearance: "dark", bg: "#0b1c24", fg: "#d7deea" },
  { slug: "cobalt-next-minimal", name: "Cobalt Next Minimal", appearance: "dark", bg: "#0b1c24", fg: "#d7deea" },
  { slug: "cobalt2", name: "Cobalt2", appearance: "dark", bg: "#132738", fg: "#ffffff" },
  { slug: "coffee-theme", name: "Coffee Theme", appearance: "light", bg: "#f5deb3", fg: "#000000" },
  { slug: "crayon-pony-fish", name: "Crayon Pony Fish", appearance: "dark", bg: "#150707", fg: "#68525a" },
  { slug: "cursor-dark", name: "Cursor Dark", appearance: "dark", bg: "#141414", fg: "#ffffff" },
  { slug: "cutie-pro", name: "Cutie Pro", appearance: "dark", bg: "#181818", fg: "#d5d0c9" },
  { slug: "cyberdyne", name: "Cyberdyne", appearance: "dark", bg: "#151144", fg: "#00ff92" },
  { slug: "cyberpunk", name: "Cyberpunk", appearance: "dark", bg: "#332a57", fg: "#e5e5e5" },
  { slug: "cyberpunk-scarlet-protocol", name: "Cyberpunk Scarlet Protocol", appearance: "dark", bg: "#101116", fg: "#e41951" },
  { slug: "dark-modern", name: "Dark Modern", appearance: "dark", bg: "#1f1f1f", fg: "#cccccc" },
  { slug: "dark-pastel", name: "Dark Pastel", appearance: "dark", bg: "#000000", fg: "#ffffff" },
  { slug: "dark", name: "Dark+", appearance: "dark", bg: "#1e1e1e", fg: "#cccccc" },
  { slug: "darkermatrix", name: "Darkermatrix", appearance: "dark", bg: "#070c0e", fg: "#35451a" },
  { slug: "darkmatrix", name: "Darkmatrix", appearance: "dark", bg: "#070c0e", fg: "#3e5715" },
  { slug: "darkside", name: "Darkside", appearance: "dark", bg: "#222324", fg: "#bababa" },
  { slug: "dawnfox", name: "Dawnfox", appearance: "light", bg: "#faf4ed", fg: "#575279" },
  { slug: "dayfox", name: "Dayfox", appearance: "light", bg: "#f6f2ee", fg: "#3d2b5a" },
  { slug: "deep", name: "Deep", appearance: "dark", bg: "#090909", fg: "#cdcdcd" },
  { slug: "desert", name: "Desert", appearance: "dark", bg: "#333333", fg: "#ffffff" },
  { slug: "detuned", name: "Detuned", appearance: "dark", bg: "#000000", fg: "#c7c7c7" },
  { slug: "dimidium", name: "Dimidium", appearance: "dark", bg: "#141414", fg: "#bab7b6" },
  { slug: "dimmed-monokai", name: "Dimmed Monokai", appearance: "dark", bg: "#1f1f1f", fg: "#b9bcba" },
  { slug: "django", name: "Django", appearance: "dark", bg: "#0b2f20", fg: "#f8f8f8" },
  { slug: "django-reborn-again", name: "Django Reborn Again", appearance: "dark", bg: "#051f14", fg: "#dadedc" },
  { slug: "django-smooth", name: "Django Smooth", appearance: "dark", bg: "#245032", fg: "#f8f8f8" },
  { slug: "doom-one", name: "Doom One", appearance: "dark", bg: "#282c34", fg: "#bbc2cf" },
  { slug: "doom-peacock", name: "Doom Peacock", appearance: "dark", bg: "#2b2a27", fg: "#ede0ce" },
  { slug: "dot-gov", name: "Dot Gov", appearance: "dark", bg: "#262c35", fg: "#ebebeb" },
  { slug: "dracula", name: "Dracula", appearance: "dark", bg: "#282a36", fg: "#f8f8f2" },
  { slug: "dracula-2", name: "Dracula+", appearance: "dark", bg: "#212121", fg: "#f8f8f2" },
  { slug: "duckbones", name: "Duckbones", appearance: "dark", bg: "#0e101a", fg: "#ebefc0" },
  { slug: "duotone-dark", name: "Duotone Dark", appearance: "dark", bg: "#1f1d27", fg: "#b7a1ff" },
  { slug: "duskfox", name: "Duskfox", appearance: "dark", bg: "#232136", fg: "#e0def4" },
  { slug: "encom", name: "ENCOM", appearance: "dark", bg: "#000000", fg: "#00a595" },
  { slug: "earthsong", name: "Earthsong", appearance: "dark", bg: "#292520", fg: "#e5c7a9" },
  { slug: "electron-highlighter", name: "Electron Highlighter", appearance: "dark", bg: "#23283d", fg: "#a5b6d4" },
  { slug: "elegant", name: "Elegant", appearance: "dark", bg: "#292b31", fg: "#ced2d6" },
  { slug: "elemental", name: "Elemental", appearance: "dark", bg: "#22211d", fg: "#807a74" },
  { slug: "elementary", name: "Elementary", appearance: "dark", bg: "#181818", fg: "#efefef" },
  { slug: "embark", name: "Embark", appearance: "dark", bg: "#1e1c31", fg: "#eeffff" },
  { slug: "embers-dark", name: "Embers Dark", appearance: "dark", bg: "#16130f", fg: "#a39a90" },
  { slug: "espresso", name: "Espresso", appearance: "dark", bg: "#323232", fg: "#ffffff" },
  { slug: "espresso-libre", name: "Espresso Libre", appearance: "dark", bg: "#2a211c", fg: "#b8a898" },
  { slug: "everblush", name: "Everblush", appearance: "dark", bg: "#141b1e", fg: "#dadada" },
  { slug: "everforest-dark-hard", name: "Everforest Dark Hard", appearance: "dark", bg: "#1e2326", fg: "#d3c6aa" },
  { slug: "everforest-light-med", name: "Everforest Light Med", appearance: "light", bg: "#efebd4", fg: "#5c6a72" },
  { slug: "fahrenheit", name: "Fahrenheit", appearance: "dark", bg: "#000000", fg: "#ffffce" },
  { slug: "fairyfloss", name: "Fairyfloss", appearance: "dark", bg: "#5a5475", fg: "#f8f8f2" },
  { slug: "farmhouse-dark", name: "Farmhouse Dark", appearance: "dark", bg: "#1d2027", fg: "#e8e4e1" },
  { slug: "farmhouse-light", name: "Farmhouse Light", appearance: "light", bg: "#e8e4e1", fg: "#1d2027" },
  { slug: "fideloper", name: "Fideloper", appearance: "dark", bg: "#292f33", fg: "#dbdae0" },
  { slug: "firefly-traditional", name: "Firefly Traditional", appearance: "dark", bg: "#000000", fg: "#f5f5f5" },
  { slug: "firefox-dev", name: "Firefox Dev", appearance: "dark", bg: "#0e1011", fg: "#7c8fa4" },
  { slug: "firewatch", name: "Firewatch", appearance: "dark", bg: "#1e2027", fg: "#9ba2b2" },
  { slug: "fish-tank", name: "Fish Tank", appearance: "dark", bg: "#232537", fg: "#ecf0fe" },
  { slug: "flat", name: "Flat", appearance: "dark", bg: "#002240", fg: "#2cc55d" },
  { slug: "flatland", name: "Flatland", appearance: "dark", bg: "#1d1f21", fg: "#b8dbef" },
  { slug: "flexoki-dark", name: "Flexoki Dark", appearance: "dark", bg: "#100f0f", fg: "#cecdc3" },
  { slug: "flexoki-light", name: "Flexoki Light", appearance: "light", bg: "#fffcf0", fg: "#100f0f" },
  { slug: "floraverse", name: "Floraverse", appearance: "dark", bg: "#0e0d15", fg: "#dbd1b9" },
  { slug: "forest-blue", name: "Forest Blue", appearance: "dark", bg: "#051519", fg: "#e2d8cd" },
  { slug: "framer", name: "Framer", appearance: "dark", bg: "#111111", fg: "#777777" },
  { slug: "front-end-delight", name: "Front End Delight", appearance: "dark", bg: "#1b1c1d", fg: "#adadad" },
  { slug: "fun-forrest", name: "Fun Forrest", appearance: "dark", bg: "#251200", fg: "#dec165" },
  { slug: "galaxy", name: "Galaxy", appearance: "dark", bg: "#1d2837", fg: "#ffffff" },
  { slug: "galizur", name: "Galizur", appearance: "dark", bg: "#071317", fg: "#ddeeff" },
  { slug: "ghostty-default-style-dark", name: "Ghostty Default Style Dark", appearance: "dark", bg: "#282c34", fg: "#ffffff" },
  { slug: "github", name: "GitHub", appearance: "light", bg: "#f4f4f4", fg: "#3e3e3e" },
  { slug: "github-dark", name: "GitHub Dark", appearance: "dark", bg: "#101216", fg: "#8b949e" },
  { slug: "github-dark-colorblind", name: "GitHub Dark Colorblind", appearance: "dark", bg: "#0d1117", fg: "#c9d1d9" },
  { slug: "github-dark-default", name: "GitHub Dark Default", appearance: "dark", bg: "#0d1117", fg: "#e6edf3" },
  { slug: "github-dark-dimmed", name: "GitHub Dark Dimmed", appearance: "dark", bg: "#22272e", fg: "#adbac7" },
  { slug: "github-dark-high-contrast", name: "GitHub Dark High Contrast", appearance: "dark", bg: "#0a0c10", fg: "#f0f3f6" },
  { slug: "github-light-colorblind", name: "GitHub Light Colorblind", appearance: "light", bg: "#ffffff", fg: "#24292f" },
  { slug: "github-light-default", name: "GitHub Light Default", appearance: "light", bg: "#ffffff", fg: "#1f2328" },
  { slug: "github-light-high-contrast", name: "GitHub Light High Contrast", appearance: "light", bg: "#ffffff", fg: "#0e1116" },
  { slug: "gitlab-dark", name: "GitLab Dark", appearance: "dark", bg: "#28262b", fg: "#ffffff" },
  { slug: "gitlab-dark-grey", name: "GitLab Dark Grey", appearance: "dark", bg: "#222222", fg: "#ffffff" },
  { slug: "gitlab-light", name: "GitLab Light", appearance: "light", bg: "#fafaff", fg: "#303030" },
  { slug: "glacier", name: "Glacier", appearance: "dark", bg: "#0c1115", fg: "#ffffff" },
  { slug: "grape", name: "Grape", appearance: "dark", bg: "#171423", fg: "#9f9fa1" },
  { slug: "grass", name: "Grass", appearance: "dark", bg: "#13773d", fg: "#fff0a5" },
  { slug: "grey-green", name: "Grey Green", appearance: "dark", bg: "#002a1a", fg: "#ffffff" },
  { slug: "gruber-darker", name: "Gruber Darker", appearance: "dark", bg: "#181818", fg: "#e4e4e4" },
  { slug: "gruvbox-dark", name: "Gruvbox Dark", appearance: "dark", bg: "#282828", fg: "#ebdbb2" },
  { slug: "gruvbox-dark-hard", name: "Gruvbox Dark Hard", appearance: "dark", bg: "#1d2021", fg: "#ebdbb2" },
  { slug: "gruvbox-light", name: "Gruvbox Light", appearance: "light", bg: "#fbf1c7", fg: "#3c3836" },
  { slug: "gruvbox-light-hard", name: "Gruvbox Light Hard", appearance: "light", bg: "#f9f5d7", fg: "#3c3836" },
  { slug: "gruvbox-material", name: "Gruvbox Material", appearance: "dark", bg: "#1d2021", fg: "#d4be98" },
  { slug: "gruvbox-material-dark", name: "Gruvbox Material Dark", appearance: "dark", bg: "#282828", fg: "#d4be98" },
  { slug: "gruvbox-material-light", name: "Gruvbox Material Light", appearance: "light", bg: "#fbf1c7", fg: "#654735" },
  { slug: "guezwhoz", name: "Guezwhoz", appearance: "dark", bg: "#1d1d1d", fg: "#d9d9d9" },
  { slug: "hax0r-blue", name: "HaX0R Blue", appearance: "dark", bg: "#010515", fg: "#11b7ff" },
  { slug: "hax0r-gr33n", name: "HaX0R Gr33N", appearance: "dark", bg: "#020f01", fg: "#16b10e" },
  { slug: "hax0r-r3d", name: "HaX0R R3D", appearance: "dark", bg: "#200101", fg: "#b10e0e" },
  { slug: "hacktober", name: "Hacktober", appearance: "dark", bg: "#141414", fg: "#c9c9c9" },
  { slug: "hardcore", name: "Hardcore", appearance: "dark", bg: "#121212", fg: "#a0a0a0" },
  { slug: "harper", name: "Harper", appearance: "dark", bg: "#010101", fg: "#a8a49d" },
  { slug: "havn-daggry", name: "Havn Daggry", appearance: "light", bg: "#f8f9fb", fg: "#3b4a7a" },
  { slug: "havn-skumring", name: "Havn Skumring", appearance: "dark", bg: "#111522", fg: "#d6dbeb" },
  { slug: "heeler", name: "Heeler", appearance: "dark", bg: "#211f46", fg: "#fdfdfd" },
  { slug: "highway", name: "Highway", appearance: "dark", bg: "#222225", fg: "#ededed" },
  { slug: "hipster-green", name: "Hipster Green", appearance: "dark", bg: "#100b05", fg: "#84c138" },
  { slug: "hivacruz", name: "Hivacruz", appearance: "dark", bg: "#132638", fg: "#ede4e4" },
  { slug: "homebrew", name: "Homebrew", appearance: "dark", bg: "#000000", fg: "#00ff00" },
  { slug: "hopscotch", name: "Hopscotch", appearance: "dark", bg: "#322931", fg: "#b9b5b8" },
  { slug: "hopscotch-256", name: "Hopscotch.256", appearance: "dark", bg: "#322931", fg: "#b9b5b8" },
  { slug: "horizon", name: "Horizon", appearance: "dark", bg: "#1c1e26", fg: "#d5d8da" },
  { slug: "horizon-bright", name: "Horizon Bright", appearance: "light", bg: "#fdf0ed", fg: "#16161d" },
  { slug: "hot-dog-stand", name: "Hot Dog Stand", appearance: "dark", bg: "#ea3323", fg: "#ffffff" },
  { slug: "hot-dog-stand-mustard", name: "Hot Dog Stand (Mustard)", appearance: "light", bg: "#ffff54", fg: "#000000" },
  { slug: "hurtado", name: "Hurtado", appearance: "dark", bg: "#000000", fg: "#dbdbdb" },
  { slug: "hybrid", name: "Hybrid", appearance: "dark", bg: "#161719", fg: "#b7bcba" },
  { slug: "ibm-5153-cga", name: "IBM 5153 CGA", appearance: "dark", bg: "#262626", fg: "#d6d6d6" },
  { slug: "ibm-5153-cga-black", name: "IBM 5153 CGA (Black)", appearance: "dark", bg: "#000000", fg: "#c4c4c4" },
  { slug: "ic-green-ppl", name: "IC Green PPL", appearance: "dark", bg: "#2c2c2c", fg: "#e0f1dc" },
  { slug: "ic-orange-ppl", name: "IC Orange PPL", appearance: "dark", bg: "#262626", fg: "#ffcb83" },
  { slug: "ir-black", name: "IR Black", appearance: "dark", bg: "#000000", fg: "#f1f1f1" },
  { slug: "irix-console", name: "IRIX Console", appearance: "dark", bg: "#0c0c0c", fg: "#f2f2f2" },
  { slug: "irix-terminal", name: "IRIX Terminal", appearance: "dark", bg: "#000043", fg: "#f2f2f2" },
  { slug: "iceberg-dark", name: "Iceberg Dark", appearance: "dark", bg: "#161821", fg: "#c6c8d1" },
  { slug: "iceberg-light", name: "Iceberg Light", appearance: "light", bg: "#e8e9ec", fg: "#33374c" },
  { slug: "idea", name: "Idea", appearance: "dark", bg: "#202020", fg: "#adadad" },
  { slug: "idle-toes", name: "Idle Toes", appearance: "dark", bg: "#323232", fg: "#ffffff" },
  { slug: "jackie-brown", name: "Jackie Brown", appearance: "dark", bg: "#2c1d16", fg: "#ffcc2f" },
  { slug: "japanesque", name: "Japanesque", appearance: "dark", bg: "#1e1e1e", fg: "#f7f6ec" },
  { slug: "jellybeans", name: "Jellybeans", appearance: "dark", bg: "#121212", fg: "#dedede" },
  { slug: "jetbrains-darcula", name: "JetBrains Darcula", appearance: "dark", bg: "#202020", fg: "#adadad" },
  { slug: "jubi", name: "Jubi", appearance: "dark", bg: "#262b33", fg: "#c3d3de" },
  { slug: "kanagawa-dragon", name: "Kanagawa Dragon", appearance: "dark", bg: "#181616", fg: "#c8c093" },
  { slug: "kanagawa-wave", name: "Kanagawa Wave", appearance: "dark", bg: "#1f1f28", fg: "#dcd7ba" },
  { slug: "kanagawabones", name: "Kanagawabones", appearance: "dark", bg: "#1f1f28", fg: "#ddd8bb" },
  { slug: "kibble", name: "Kibble", appearance: "dark", bg: "#0e100a", fg: "#f7f7f7" },
  { slug: "kitty-default", name: "Kitty Default", appearance: "dark", bg: "#000000", fg: "#dddddd" },
  { slug: "kitty-low-contrast", name: "Kitty Low Contrast", appearance: "dark", bg: "#333333", fg: "#ffffff" },
  { slug: "kolorit", name: "Kolorit", appearance: "dark", bg: "#1d1a1e", fg: "#efecec" },
  { slug: "konsolas", name: "Konsolas", appearance: "dark", bg: "#060606", fg: "#c8c1c1" },
  { slug: "kurokula", name: "Kurokula", appearance: "dark", bg: "#141515", fg: "#e0cfc2" },
  { slug: "lab-fox", name: "Lab Fox", appearance: "dark", bg: "#2e2e2e", fg: "#ffffff" },
  { slug: "laser", name: "Laser", appearance: "dark", bg: "#030d18", fg: "#f106e3" },
  { slug: "later-this-evening", name: "Later This Evening", appearance: "dark", bg: "#222222", fg: "#959595" },
  { slug: "lavandula", name: "Lavandula", appearance: "dark", bg: "#050014", fg: "#736e7d" },
  { slug: "light-owl", name: "Light Owl", appearance: "light", bg: "#fbfbfb", fg: "#403f53" },
  { slug: "liquid-carbon", name: "Liquid Carbon", appearance: "dark", bg: "#303030", fg: "#afc2c2" },
  { slug: "liquid-carbon-transparent", name: "Liquid Carbon Transparent", appearance: "dark", bg: "#000000", fg: "#afc2c2" },
  { slug: "lovelace", name: "Lovelace", appearance: "dark", bg: "#1d1f28", fg: "#fdfdfd" },
  { slug: "man-page", name: "Man Page", appearance: "light", bg: "#fef49c", fg: "#000000" },
  { slug: "mariana", name: "Mariana", appearance: "dark", bg: "#343d46", fg: "#d8dee9" },
  { slug: "material", name: "Material", appearance: "light", bg: "#eaeaea", fg: "#232322" },
  { slug: "material-dark", name: "Material Dark", appearance: "dark", bg: "#232322", fg: "#e5e5e5" },
  { slug: "material-darker", name: "Material Darker", appearance: "dark", bg: "#212121", fg: "#eeffff" },
  { slug: "material-design-colors", name: "Material Design Colors", appearance: "dark", bg: "#1d262a", fg: "#e7ebed" },
  { slug: "material-ocean", name: "Material Ocean", appearance: "dark", bg: "#0f111a", fg: "#8f93a2" },
  { slug: "mathias", name: "Mathias", appearance: "dark", bg: "#000000", fg: "#bbbbbb" },
  { slug: "matrix", name: "Matrix", appearance: "dark", bg: "#0f191c", fg: "#426644" },
  { slug: "matte-black", name: "Matte Black", appearance: "dark", bg: "#121212", fg: "#bebebe" },
  { slug: "medallion", name: "Medallion", appearance: "dark", bg: "#1d1908", fg: "#cac296" },
  { slug: "melange-dark", name: "Melange Dark", appearance: "dark", bg: "#292522", fg: "#ece1d7" },
  { slug: "melange-light", name: "Melange Light", appearance: "light", bg: "#f1f1f1", fg: "#54433a" },
  { slug: "mellifluous", name: "Mellifluous", appearance: "dark", bg: "#1a1a1a", fg: "#dadada" },
  { slug: "mellow", name: "Mellow", appearance: "dark", bg: "#161617", fg: "#c9c7cd" },
  { slug: "miasma", name: "Miasma", appearance: "dark", bg: "#222222", fg: "#c2c2b0" },
  { slug: "midnight-in-mojave", name: "Midnight In Mojave", appearance: "dark", bg: "#1e1e1e", fg: "#ffffff" },
  { slug: "mirage", name: "Mirage", appearance: "dark", bg: "#1b2738", fg: "#a6b2c0" },
  { slug: "misterioso", name: "Misterioso", appearance: "dark", bg: "#2d3743", fg: "#e1e1e0" },
  { slug: "molokai", name: "Molokai", appearance: "dark", bg: "#121212", fg: "#bbbbbb" },
  { slug: "mona-lisa", name: "Mona Lisa", appearance: "dark", bg: "#120b0d", fg: "#f7d66a" },
  { slug: "monokai-classic", name: "Monokai Classic", appearance: "dark", bg: "#272822", fg: "#fdfff1" },
  { slug: "monokai-pro", name: "Monokai Pro", appearance: "dark", bg: "#2d2a2e", fg: "#fcfcfa" },
  { slug: "monokai-pro-light", name: "Monokai Pro Light", appearance: "light", bg: "#faf4f2", fg: "#29242a" },
  { slug: "monokai-pro-light-sun", name: "Monokai Pro Light Sun", appearance: "light", bg: "#f8efe7", fg: "#2c232e" },
  { slug: "monokai-pro-machine", name: "Monokai Pro Machine", appearance: "dark", bg: "#273136", fg: "#f2fffc" },
  { slug: "monokai-pro-octagon", name: "Monokai Pro Octagon", appearance: "dark", bg: "#282a3a", fg: "#eaf2f1" },
  { slug: "monokai-pro-ristretto", name: "Monokai Pro Ristretto", appearance: "dark", bg: "#2c2525", fg: "#fff1f3" },
  { slug: "monokai-pro-spectrum", name: "Monokai Pro Spectrum", appearance: "dark", bg: "#222222", fg: "#f7f1ff" },
  { slug: "monokai-remastered", name: "Monokai Remastered", appearance: "dark", bg: "#0c0c0c", fg: "#d9d9d9" },
  { slug: "monokai-soda", name: "Monokai Soda", appearance: "dark", bg: "#1a1a1a", fg: "#c4c5b5" },
  { slug: "monokai-vivid", name: "Monokai Vivid", appearance: "dark", bg: "#121212", fg: "#f9f9f9" },
  { slug: "moonfly", name: "Moonfly", appearance: "dark", bg: "#080808", fg: "#bdbdbd" },
  { slug: "n0tch2k", name: "N0Tch2K", appearance: "dark", bg: "#222222", fg: "#a0a0a0" },
  { slug: "neobones-dark", name: "Neobones Dark", appearance: "dark", bg: "#0f191f", fg: "#c6d5cf" },
  { slug: "neobones-light", name: "Neobones Light", appearance: "light", bg: "#e5ede6", fg: "#202e18" },
  { slug: "neon", name: "Neon", appearance: "dark", bg: "#14161a", fg: "#00fffc" },
  { slug: "neopolitan", name: "Neopolitan", appearance: "dark", bg: "#271f19", fg: "#ffffff" },
  { slug: "neutron", name: "Neutron", appearance: "dark", bg: "#1c1e22", fg: "#e6e8ef" },
  { slug: "night-lion-v1", name: "Night Lion V1", appearance: "dark", bg: "#000000", fg: "#bbbbbb" },
  { slug: "night-lion-v2", name: "Night Lion V2", appearance: "dark", bg: "#171717", fg: "#bbbbbb" },
  { slug: "night-owl", name: "Night Owl", appearance: "dark", bg: "#011627", fg: "#d6deeb" },
  { slug: "night-owlish-light", name: "Night Owlish Light", appearance: "light", bg: "#ffffff", fg: "#403f53" },
  { slug: "nightfox", name: "Nightfox", appearance: "dark", bg: "#192330", fg: "#cdcecf" },
  { slug: "niji", name: "Niji", appearance: "dark", bg: "#141515", fg: "#ffffff" },
  { slug: "nocturnal-winter", name: "Nocturnal Winter", appearance: "dark", bg: "#0d0d17", fg: "#e6e5e5" },
  { slug: "nord", name: "Nord", appearance: "dark", bg: "#2e3440", fg: "#d8dee9" },
  { slug: "nord-light", name: "Nord Light", appearance: "light", bg: "#e5e9f0", fg: "#414858" },
  { slug: "nord-wave", name: "Nord Wave", appearance: "dark", bg: "#212121", fg: "#d8dee9" },
  { slug: "nordfox", name: "Nordfox", appearance: "dark", bg: "#2e3440", fg: "#cdcecf" },
  { slug: "novel", name: "Novel", appearance: "light", bg: "#dfdbc3", fg: "#3b2322" },
  { slug: "nvim-dark", name: "Nvim Dark", appearance: "dark", bg: "#14161b", fg: "#e0e2ea" },
  { slug: "nvim-light", name: "Nvim Light", appearance: "light", bg: "#e0e2ea", fg: "#14161b" },
  { slug: "obsidian", name: "Obsidian", appearance: "dark", bg: "#283033", fg: "#cdcdcd" },
  { slug: "ocean", name: "Ocean", appearance: "dark", bg: "#224fbc", fg: "#ffffff" },
  { slug: "oceanic-material", name: "Oceanic Material", appearance: "dark", bg: "#1c262b", fg: "#c2c8d7" },
  { slug: "oceanic-next", name: "Oceanic Next", appearance: "dark", bg: "#162c35", fg: "#c0c5ce" },
  { slug: "ollie", name: "Ollie", appearance: "dark", bg: "#222125", fg: "#8a8dae" },
  { slug: "one-double-dark", name: "One Double Dark", appearance: "dark", bg: "#282c34", fg: "#dbdfe5" },
  { slug: "one-double-light", name: "One Double Light", appearance: "light", bg: "#fafafa", fg: "#383a43" },
  { slug: "one-half-dark", name: "One Half Dark", appearance: "dark", bg: "#282c34", fg: "#dcdfe4" },
  { slug: "one-half-light", name: "One Half Light", appearance: "light", bg: "#fafafa", fg: "#383a42" },
  { slug: "operator-mono-dark", name: "Operator Mono Dark", appearance: "dark", bg: "#191919", fg: "#c3cac2" },
  { slug: "overnight-slumber", name: "Overnight Slumber", appearance: "dark", bg: "#0e1729", fg: "#ced2d6" },
  { slug: "oxocarbon", name: "Oxocarbon", appearance: "dark", bg: "#161616", fg: "#f2f4f8" },
  { slug: "pale-night-hc", name: "Pale Night Hc", appearance: "dark", bg: "#3e4251", fg: "#cccccc" },
  { slug: "pandora", name: "Pandora", appearance: "dark", bg: "#141e43", fg: "#e1e1e1" },
  { slug: "paraiso-dark", name: "Paraiso Dark", appearance: "dark", bg: "#2f1e2e", fg: "#a39e9b" },
  { slug: "paul-millr", name: "Paul Millr", appearance: "dark", bg: "#000000", fg: "#f2f2f2" },
  { slug: "pencil-dark", name: "Pencil Dark", appearance: "dark", bg: "#212121", fg: "#f1f1f1" },
  { slug: "pencil-light", name: "Pencil Light", appearance: "light", bg: "#f1f1f1", fg: "#424242" },
  { slug: "peppermint", name: "Peppermint", appearance: "dark", bg: "#000000", fg: "#c8c8c8" },
  { slug: "phala-green-dark", name: "Phala Green Dark", appearance: "dark", bg: "#000000", fg: "#c1fc03" },
  { slug: "piatto-light", name: "Piatto Light", appearance: "light", bg: "#ffffff", fg: "#414141" },
  { slug: "pnevma", name: "Pnevma", appearance: "dark", bg: "#1c1c1c", fg: "#d0d0d0" },
  { slug: "popping-and-locking", name: "Popping And Locking", appearance: "dark", bg: "#181921", fg: "#ebdbb2" },
  { slug: "powershell", name: "Powershell", appearance: "dark", bg: "#052454", fg: "#f6f6f7" },
  { slug: "primary", name: "Primary", appearance: "light", bg: "#ffffff", fg: "#000000" },
  { slug: "pro", name: "Pro", appearance: "dark", bg: "#000000", fg: "#f2f2f2" },
  { slug: "pro-light", name: "Pro Light", appearance: "light", bg: "#ffffff", fg: "#191919" },
  { slug: "purple-rain", name: "Purple Rain", appearance: "dark", bg: "#21084a", fg: "#fffbf6" },
  { slug: "purplepeter", name: "Purplepeter", appearance: "dark", bg: "#2a1a4a", fg: "#ece7fa" },
  { slug: "rapture", name: "Rapture", appearance: "dark", bg: "#111e2a", fg: "#c0c9e5" },
  { slug: "raycast-dark", name: "Raycast Dark", appearance: "dark", bg: "#1a1a1a", fg: "#ffffff" },
  { slug: "raycast-light", name: "Raycast Light", appearance: "light", bg: "#ffffff", fg: "#000000" },
  { slug: "rebecca", name: "Rebecca", appearance: "dark", bg: "#292a44", fg: "#e8e6ed" },
  { slug: "red-alert", name: "Red Alert", appearance: "dark", bg: "#762423", fg: "#ffffff" },
  { slug: "red-planet", name: "Red Planet", appearance: "dark", bg: "#222222", fg: "#c2b790" },
  { slug: "red-sands", name: "Red Sands", appearance: "dark", bg: "#7a251e", fg: "#d7c9a7" },
  { slug: "relaxed", name: "Relaxed", appearance: "dark", bg: "#353a44", fg: "#d9d9d9" },
  { slug: "retro", name: "Retro", appearance: "dark", bg: "#000000", fg: "#13a10e" },
  { slug: "retro-legends", name: "Retro Legends", appearance: "dark", bg: "#0d0d0d", fg: "#45eb45" },
  { slug: "rippedcasts", name: "Rippedcasts", appearance: "dark", bg: "#2b2b2b", fg: "#ffffff" },
  { slug: "rose-pine", name: "Rose Pine", appearance: "dark", bg: "#191724", fg: "#e0def4" },
  { slug: "rose-pine-dawn", name: "Rose Pine Dawn", appearance: "light", bg: "#faf4ed", fg: "#575279" },
  { slug: "rose-pine-moon", name: "Rose Pine Moon", appearance: "dark", bg: "#232136", fg: "#e0def4" },
  { slug: "rouge-2", name: "Rouge 2", appearance: "dark", bg: "#17182b", fg: "#a2a3aa" },
  { slug: "royal", name: "Royal", appearance: "dark", bg: "#100815", fg: "#514968" },
  { slug: "ryuuko", name: "Ryuuko", appearance: "dark", bg: "#2c3941", fg: "#ececec" },
  { slug: "sakura", name: "Sakura", appearance: "dark", bg: "#18131e", fg: "#dd7bdc" },
  { slug: "scarlet-protocol", name: "Scarlet Protocol", appearance: "dark", bg: "#1c153d", fg: "#e41951" },
  { slug: "sea-shells", name: "Sea Shells", appearance: "dark", bg: "#09141b", fg: "#deb88d" },
  { slug: "seafoam-pastel", name: "Seafoam Pastel", appearance: "dark", bg: "#243435", fg: "#d4e7d4" },
  { slug: "selenized-dark", name: "Selenized Dark", appearance: "dark", bg: "#103c48", fg: "#adbcbc" },
  { slug: "selenized-light", name: "Selenized Light", appearance: "light", bg: "#fbf3db", fg: "#53676d" },
  { slug: "seoulbones-dark", name: "Seoulbones Dark", appearance: "dark", bg: "#4b4b4b", fg: "#dddddd" },
  { slug: "seoulbones-light", name: "Seoulbones Light", appearance: "light", bg: "#e2e2e2", fg: "#555555" },
  { slug: "seti", name: "Seti", appearance: "dark", bg: "#111213", fg: "#cacecd" },
  { slug: "shades-of-purple", name: "Shades Of Purple", appearance: "dark", bg: "#1e1d40", fg: "#ffffff" },
  { slug: "shaman", name: "Shaman", appearance: "dark", bg: "#001015", fg: "#405555" },
  { slug: "slate", name: "Slate", appearance: "dark", bg: "#222222", fg: "#35b1d2" },
  { slug: "sleepy-hollow", name: "Sleepy Hollow", appearance: "dark", bg: "#121214", fg: "#af9a91" },
  { slug: "smyck", name: "Smyck", appearance: "dark", bg: "#1b1b1b", fg: "#f7f7f7" },
  { slug: "snazzy", name: "Snazzy", appearance: "dark", bg: "#1e1f29", fg: "#ebece6" },
  { slug: "snazzy-soft", name: "Snazzy Soft", appearance: "dark", bg: "#282a36", fg: "#eff0eb" },
  { slug: "soft-server", name: "Soft Server", appearance: "dark", bg: "#242626", fg: "#99a3a2" },
  { slug: "solarized-darcula", name: "Solarized Darcula", appearance: "dark", bg: "#3d3f41", fg: "#d2d8d9" },
  { slug: "solarized-dark-higher-contrast", name: "Solarized Dark Higher Contrast", appearance: "dark", bg: "#001e27", fg: "#9cc2c3" },
  { slug: "solarized-dark-patched", name: "Solarized Dark Patched", appearance: "dark", bg: "#001e27", fg: "#708284" },
  { slug: "solarized-osaka-night", name: "Solarized Osaka Night", appearance: "dark", bg: "#1a1b26", fg: "#c0caf5" },
  { slug: "sonokai", name: "Sonokai", appearance: "dark", bg: "#2c2e34", fg: "#e2e2e3" },
  { slug: "spacedust", name: "Spacedust", appearance: "dark", bg: "#0a1e24", fg: "#ecf0c1" },
  { slug: "spacegray", name: "Spacegray", appearance: "dark", bg: "#20242d", fg: "#b3b8c3" },
  { slug: "spacegray-bright", name: "Spacegray Bright", appearance: "dark", bg: "#2a2e3a", fg: "#f3f3f3" },
  { slug: "spacegray-eighties", name: "Spacegray Eighties", appearance: "dark", bg: "#222222", fg: "#bdbaae" },
  { slug: "spacegray-eighties-dull", name: "Spacegray Eighties Dull", appearance: "dark", bg: "#222222", fg: "#c9c6bc" },
  { slug: "spiderman", name: "Spiderman", appearance: "dark", bg: "#1b1d1e", fg: "#e3e3e3" },
  { slug: "spring", name: "Spring", appearance: "light", bg: "#ffffff", fg: "#4d4d4c" },
  { slug: "square", name: "Square", appearance: "dark", bg: "#1a1a1a", fg: "#acacab" },
  { slug: "squirrelsong-dark", name: "Squirrelsong Dark", appearance: "dark", bg: "#372920", fg: "#b19b89" },
  { slug: "srcery", name: "Srcery", appearance: "dark", bg: "#1c1b19", fg: "#fce8c3" },
  { slug: "starlight", name: "Starlight", appearance: "dark", bg: "#242424", fg: "#ffffff" },
  { slug: "sublette", name: "Sublette", appearance: "dark", bg: "#202535", fg: "#ccced0" },
  { slug: "subliminal", name: "Subliminal", appearance: "dark", bg: "#282c35", fg: "#d4d4d4" },
  { slug: "sugarplum", name: "Sugarplum", appearance: "dark", bg: "#111147", fg: "#db7ddd" },
  { slug: "sundried", name: "Sundried", appearance: "dark", bg: "#1a1818", fg: "#c9c9c9" },
  { slug: "symfonic", name: "Symfonic", appearance: "dark", bg: "#000000", fg: "#ffffff" },
  { slug: "synthwave", name: "Synthwave", appearance: "dark", bg: "#000000", fg: "#dad9c7" },
  { slug: "synthwave-alpha", name: "Synthwave Alpha", appearance: "dark", bg: "#241b30", fg: "#f2f2e3" },
  { slug: "synthwave-everything", name: "Synthwave Everything", appearance: "dark", bg: "#2a2139", fg: "#f0eff1" },
  { slug: "tango-adapted", name: "Tango Adapted", appearance: "light", bg: "#ffffff", fg: "#000000" },
  { slug: "tango-half-adapted", name: "Tango Half Adapted", appearance: "light", bg: "#ffffff", fg: "#000000" },
  { slug: "tearout", name: "Tearout", appearance: "dark", bg: "#34392d", fg: "#f4d2ae" },
  { slug: "teerb", name: "Teerb", appearance: "dark", bg: "#262626", fg: "#d0d0d0" },
  { slug: "terafox", name: "Terafox", appearance: "dark", bg: "#152528", fg: "#e6eaea" },
  { slug: "terminal-basic", name: "Terminal Basic", appearance: "light", bg: "#ffffff", fg: "#000000" },
  { slug: "terminal-basic-dark", name: "Terminal Basic Dark", appearance: "dark", bg: "#1d1e1d", fg: "#ffffff" },
  { slug: "thayer-bright", name: "Thayer Bright", appearance: "dark", bg: "#1b1d1e", fg: "#f8f8f8" },
  { slug: "the-hulk", name: "The Hulk", appearance: "dark", bg: "#1b1d1e", fg: "#b5b5b5" },
  { slug: "tinacious-design-dark", name: "Tinacious Design Dark", appearance: "dark", bg: "#1d1d26", fg: "#cbcbf0" },
  { slug: "tinacious-design-light", name: "Tinacious Design Light", appearance: "light", bg: "#f8f8ff", fg: "#1d1d26" },
  { slug: "tokyonight", name: "TokyoNight", appearance: "dark", bg: "#1a1b26", fg: "#c0caf5" },
  { slug: "tokyonight-day", name: "TokyoNight Day", appearance: "light", bg: "#e1e2e7", fg: "#3760bf" },
  { slug: "tokyonight-moon", name: "TokyoNight Moon", appearance: "dark", bg: "#222436", fg: "#c8d3f5" },
  { slug: "tokyonight-night", name: "TokyoNight Night", appearance: "dark", bg: "#1a1b26", fg: "#c0caf5" },
  { slug: "tokyonight-storm", name: "TokyoNight Storm", appearance: "dark", bg: "#24283b", fg: "#c0caf5" },
  { slug: "tomorrow", name: "Tomorrow", appearance: "light", bg: "#ffffff", fg: "#4d4d4c" },
  { slug: "tomorrow-night", name: "Tomorrow Night", appearance: "dark", bg: "#1d1f21", fg: "#c5c8c6" },
  { slug: "tomorrow-night-blue", name: "Tomorrow Night Blue", appearance: "dark", bg: "#002451", fg: "#ffffff" },
  { slug: "tomorrow-night-bright", name: "Tomorrow Night Bright", appearance: "dark", bg: "#000000", fg: "#eaeaea" },
  { slug: "tomorrow-night-burns", name: "Tomorrow Night Burns", appearance: "dark", bg: "#151515", fg: "#a1b0b8" },
  { slug: "tomorrow-night-eighties", name: "Tomorrow Night Eighties", appearance: "dark", bg: "#2d2d2d", fg: "#cccccc" },
  { slug: "toy-chest", name: "Toy Chest", appearance: "dark", bg: "#24364b", fg: "#31d07b" },
  { slug: "treehouse", name: "Treehouse", appearance: "dark", bg: "#191919", fg: "#786b53" },
  { slug: "twilight", name: "Twilight", appearance: "dark", bg: "#141414", fg: "#ffffd4" },
  { slug: "ubuntu", name: "Ubuntu", appearance: "dark", bg: "#300a24", fg: "#eeeeec" },
  { slug: "ultra-dark", name: "Ultra Dark", appearance: "dark", bg: "#000000", fg: "#ffffff" },
  { slug: "ultra-violent", name: "Ultra Violent", appearance: "dark", bg: "#242728", fg: "#c1c1c1" },
  { slug: "under-the-sea", name: "Under The Sea", appearance: "dark", bg: "#011116", fg: "#ffffff" },
  { slug: "unikitty", name: "Unikitty", appearance: "light", bg: "#ff8cd9", fg: "#0b0b0b" },
  { slug: "urple", name: "Urple", appearance: "dark", bg: "#1b1b23", fg: "#877a9b" },
  { slug: "vague", name: "Vague", appearance: "dark", bg: "#141415", fg: "#cdcdcd" },
  { slug: "vaughn", name: "Vaughn", appearance: "dark", bg: "#25234f", fg: "#dcdccc" },
  { slug: "vercel", name: "Vercel", appearance: "dark", bg: "#101010", fg: "#fafafa" },
  { slug: "vesper", name: "Vesper", appearance: "dark", bg: "#101010", fg: "#ffffff" },
  { slug: "vibrant-ink", name: "Vibrant Ink", appearance: "dark", bg: "#000000", fg: "#ffffff" },
  { slug: "vimbones", name: "Vimbones", appearance: "light", bg: "#f0f0ca", fg: "#353535" },
  { slug: "violet-dark", name: "Violet Dark", appearance: "dark", bg: "#1c1d1f", fg: "#708284" },
  { slug: "violet-light", name: "Violet Light", appearance: "light", bg: "#fcf4dc", fg: "#536870" },
  { slug: "violite", name: "Violite", appearance: "dark", bg: "#241c36", fg: "#eef4f6" },
  { slug: "warm-neon", name: "Warm Neon", appearance: "dark", bg: "#404040", fg: "#afdab6" },
  { slug: "wez", name: "Wez", appearance: "dark", bg: "#000000", fg: "#b3b3b3" },
  { slug: "whimsy", name: "Whimsy", appearance: "dark", bg: "#29283b", fg: "#b3b0d6" },
  { slug: "wild-cherry", name: "Wild Cherry", appearance: "dark", bg: "#1f1726", fg: "#dafaff" },
  { slug: "wilmersdorf", name: "Wilmersdorf", appearance: "dark", bg: "#282b33", fg: "#c6c6c6" },
  { slug: "wombat", name: "Wombat", appearance: "dark", bg: "#171717", fg: "#dedacf" },
  { slug: "wryan", name: "Wryan", appearance: "dark", bg: "#101010", fg: "#999993" },
  { slug: "xcode-dark", name: "Xcode Dark", appearance: "dark", bg: "#292a30", fg: "#dfdfe0" },
  { slug: "xcode-dark-hc", name: "Xcode Dark hc", appearance: "dark", bg: "#1f1f24", fg: "#ffffff" },
  { slug: "xcode-light", name: "Xcode Light", appearance: "light", bg: "#ffffff", fg: "#262626" },
  { slug: "xcode-light-hc", name: "Xcode Light hc", appearance: "light", bg: "#ffffff", fg: "#000000" },
  { slug: "xcode-wwdc", name: "Xcode WWDC", appearance: "dark", bg: "#292c36", fg: "#e7e8eb" },
  { slug: "zenbones", name: "Zenbones", appearance: "light", bg: "#f0edec", fg: "#2c363c" },
  { slug: "zenbones-dark", name: "Zenbones Dark", appearance: "dark", bg: "#1c1917", fg: "#b4bdc3" },
  { slug: "zenbones-light", name: "Zenbones Light", appearance: "light", bg: "#f0edec", fg: "#2c363c" },
  { slug: "zenburn", name: "Zenburn", appearance: "dark", bg: "#3f3f3f", fg: "#dcdccc" },
  { slug: "zenburned", name: "Zenburned", appearance: "dark", bg: "#404040", fg: "#f0e4cf" },
  { slug: "zenwritten-dark", name: "Zenwritten Dark", appearance: "dark", bg: "#191919", fg: "#bbbbbb" },
  { slug: "zenwritten-light", name: "Zenwritten Light", appearance: "light", bg: "#eeeeee", fg: "#353535" },
  { slug: "iterm2-dark-background", name: "iTerm2 Dark Background", appearance: "dark", bg: "#000000", fg: "#c7c7c7" },
  { slug: "iterm2-default", name: "iTerm2 Default", appearance: "dark", bg: "#000000", fg: "#ffffff" },
  { slug: "iterm2-light-background", name: "iTerm2 Light Background", appearance: "light", bg: "#ffffff", fg: "#000000" },
  { slug: "iterm2-pastel-dark-background", name: "iTerm2 Pastel Dark Background", appearance: "dark", bg: "#000000", fg: "#c7c7c7" },
  { slug: "iterm2-smoooooth", name: "iTerm2 Smoooooth", appearance: "dark", bg: "#15191f", fg: "#dcdcdc" },
  { slug: "iterm2-solarized-dark", name: "iTerm2 Solarized Dark", appearance: "dark", bg: "#002b36", fg: "#839496" },
  { slug: "iterm2-solarized-light", name: "iTerm2 Solarized Light", appearance: "light", bg: "#fdf6e3", fg: "#657b83" },
  { slug: "iterm2-tango-dark", name: "iTerm2 Tango Dark", appearance: "dark", bg: "#000000", fg: "#ffffff" },
  { slug: "iterm2-tango-light", name: "iTerm2 Tango Light", appearance: "light", bg: "#ffffff", fg: "#000000" },
]
